
import { createClient } from '@supabase/supabase-js';

const supabaseUrl = process.env.SUPABASE_URL || 'https://vufysvncrrmyheyyyysu.supabase.co';
const supabaseAnonKey = process.env.SUPABASE_ANON_KEY || 'sb_publishable_sIc1FTJ4veBw0vx6rJkO8w_r4km2EiM';

export const supabase = createClient(supabaseUrl, supabaseAnonKey);

/**
 * Converts object keys to snake_case and filters out null/undefined values.
 */
const toSnakeCase = (obj: any, excludeKeys: string[] = []) => {
  if (!obj || typeof obj !== 'object' || Array.isArray(obj)) return obj;
  const result: any = {};
  for (const key in obj) {
    if (Object.prototype.hasOwnProperty.call(obj, key)) {
      // Skip undefined or null values
      if (obj[key] === undefined || obj[key] === null) continue;
      
      const snakeKey = key.replace(/[A-Z]/g, letter => `_${letter.toLowerCase()}`);
      
      // Filter out specifically problematic keys if any
      if (excludeKeys.includes(snakeKey)) continue;
      
      result[snakeKey] = obj[key];
    }
  }
  return result;
};

const toCamelCase = (obj: any) => {
  if (!obj || typeof obj !== 'object' || Array.isArray(obj)) return obj;
  const result: any = {};
  for (const key in obj) {
    if (Object.prototype.hasOwnProperty.call(obj, key)) {
      const camelKey = key.replace(/([-_][a-z])/gi, ($1) => {
        return $1.toUpperCase().replace('-', '').replace('_', '');
      });
      result[camelKey] = obj[key];
    }
  }
  return result;
};

export const dbService = {
  async fetchAll(table: string) {
    try {
      const { data, error } = await supabase.from(table).select('*');
      if (error) throw error;
      
      if (table === 'subject_list') {
        const settings = data?.find(item => item.id === 'current_subjects');
        return settings ? settings.list : [];
      }

      if (table === 'school_branding') {
        const branding = data?.find(item => item.id === 'active_brand');
        return branding ? toCamelCase(branding) : null;
      }
      
      return (data || []).map(item => toCamelCase(item));
    } catch (err) {
      console.warn(`Sync Warning [${table}]:`, err);
      return [];
    }
  },

  async upsert(table: string, payload: any) {
    try {
      let dataToPush: any;
      const exclude: string[] = [];

      if (table === 'subject_list') {
        dataToPush = { id: 'current_subjects', list: payload };
      } else if (table === 'school_branding') {
        dataToPush = { ...toSnakeCase(payload, exclude), id: 'active_brand' };
      } else if (Array.isArray(payload)) {
        // Handle bulk updates (like Attendance)
        dataToPush = payload.map(item => {
          const cleaned = { ...item };
          // If id is null, undefined, 0, or a placeholder string, remove it 
          // to let Supabase's BIGINT GENERATED BY DEFAULT AS IDENTITY handle it.
          if (!cleaned.id || (typeof cleaned.id === 'string' && (cleaned.id.includes('.') || isNaN(Number(cleaned.id))))) {
             delete cleaned.id; 
          }
          return toSnakeCase(cleaned, exclude);
        });
      } else {
        const cleaned = { ...payload };
        // Logic for single row upsert (Students, Teachers, etc.)
        // Only keep ID if it's a valid string ID (UUID/Custom)
        if (!cleaned.id) delete cleaned.id;
        dataToPush = toSnakeCase(cleaned, exclude);
      }
      
      let onConflict = 'id';
      if (table === 'food_chart') onConflict = 'day';
      if (table === 'fee_structures') onConflict = 'grade';
      if (table === 'attendance') onConflict = 'date,student_id';

      const { error } = await supabase.from(table).upsert(dataToPush, { 
        onConflict,
        ignoreDuplicates: false 
      });
      
      if (error) throw error;
    } catch (err) {
      console.error(`Upsert Error [${table}]:`, err);
      throw err;
    }
  },

  async delete(table: string, id: string) {
    try {
      let pk = 'id';
      if (table === 'food_chart') pk = 'day';
      if (table === 'fee_structures') pk = 'grade';
      
      const { error } = await supabase.from(table).delete().eq(pk, id);
      if (error) throw error;
      console.log(`Sync Success: Item ${id} deleted from ${table}`);
    } catch (err) {
      console.error(`Delete Error [${table}]:`, err);
      throw err;
    }
  }
};
